### ISSUE TITLE
support M-numbers

### ISSUE THREAD

**Issue by ghost** [lucaswerkmeister/tool-wd-image-positions#3]
Then 'By item and property' and 'By file' can be the same entry box.

**Comment by lucaswerkmeister** [comment]
> Then 'By item and property' and 'By file' can be the same entry box.

I disagree, “by property” doesn’t make sense for MediaInfo entities (since the image is the file the entity belongs to, not the value of any statement). But I guess I can at least recognize MediaInfo IDs in that section of the form and redirect accordingly as long as the property has been left empty.

**Comment by lucaswerkmeister** [comment]
(Also, requiring users to input MediaInfo IDs sounds much less convenient than an input for file names…)

**Comment by ghost** [comment]
Fair, I just wasn't sure to what extent the tool made assumptions that required Wikibase entities to point towards.

**Comment by lucaswerkmeister** [comment]
Putting an M-ID into the “by file” section works now.
